### ISSUE TITLE
*.svg icons for OAUTH login buttons

### ISSUE THREAD

**Issue by MythicAngel** [AhmedMRaihan/allOAuth#2]
At the moment, OAUTH buttons for logging to Google/Facebook are some random button downloaded from internet and displayed by resizing (which reduce quality immensely in mobile devices)

It would be better to have them as *.svg so that they're scalable to any size.

**Comment by AhmedMRaihan** [comment]
Google image guideline and branding images: https://developers.google.com/identity/branding-guidelines

**Comment by AhmedMRaihan** [comment]
Facebook button designing guideline and resource here: https://developers.facebook.com/docs/facebook-login/userexperience/#buttondesign
